### ISSUE TITLE
Activity - Speaker Details

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/GDGPune-DevFest19-Android#11]
New activity for Speaker profile view. It will include-
- Circular Profile Picture
- Name
- Designation
- Introduction
- Social Links

**Comment by drigio** [comment]
I would like to work on this! @PatilShreyas

**Comment by PatilShreyas** [comment]
@drigio Sure! Send a PR.

**Comment by PatilShreyas** [comment]
Pending:
Make Translucent status bar and Transparent ActionBar for CircularImageView to look good.

**Comment by PatilShreyas** [comment]
Implemented! Thanks @drigio.
